//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bukka2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public decimal FoodPrice { get; set; }
        public string FoodName { get; set; }
    }
}
